// Mock Agents
export const mockAgents = [
    {
      id: "agent1",
      name: "Sarah Johnson",
      email: "sarah.johnson@realestate.com",
      phone: "(123) 456-7890",
      photo: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "agent2",
      name: "Michael Chen",
      email: "michael.chen@realestate.com",
      phone: "(123) 456-7891",
      photo: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "agent3",
      name: "Jessica Williams",
      email: "jessica.williams@realestate.com",
      phone: "(123) 456-7892",
      photo: "/placeholder.svg?height=200&width=200",
    },
  ]
  
  // Mock Properties
  export const mockProperties = [
    {
      id: "prop1",
      title: "Modern Downtown Apartment",
      description:
        "Luxurious 2-bedroom apartment in the heart of downtown with stunning city views, modern appliances, and access to premium amenities including a gym, pool, and rooftop terrace.",
      price: 450000,
      type: "sale",
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 1200,
      location: "123 Main St, New York, NY",
      images: [
        "/images/placeholder.svg",
        "/images/placeholder.svg",
        "/images/placeholder.svg",
      ],
      features: ["Hardwood Floors", "Central AC", "In-unit Laundry", "Balcony", "Parking"],
      yearBuilt: 2018,
      agent: mockAgents[0],
      reviews: [
        {
          id: "rev1",
          userId: "user1",
          userName: "John Doe",
          rating: 4,
          comment: "Great property, excellent location!",
          date: "2023-05-15",
        },
      ],
    },
    {
      id: "prop2",
      title: "Spacious Family Home",
      description:
        "Beautiful 4-bedroom family home in a quiet suburban neighborhood with a large backyard, updated kitchen, and finished basement.",
      price: 750000,
      type: "sale",
      bedrooms: 4,
      bathrooms: 3,
      squareFeet: 2800,
      location: "456 Oak Ave, Chicago, IL",
      images: [
        "/images/placeholder.svg",
        "/images/placeholder.svg",
        "/images/placeholder.svg",
      ],
      features: ["Finished Basement", "Backyard", "Garage", "Fireplace", "Updated Kitchen"],
      yearBuilt: 2005,
      agent: mockAgents[1],
    },
    {
      id: "prop3",
      title: "Luxury Waterfront Condo",
      description:
        "Stunning 3-bedroom waterfront condo with panoramic ocean views, high-end finishes, and resort-style amenities.",
      price: 1200000,
      type: "sale",
      bedrooms: 3,
      bathrooms: 3.5,
      squareFeet: 2200,
      location: "789 Beach Blvd, Miami, FL",
      images: [
        "/images/placeholder.svg",
        "/images/placeholder.svg",
        "/images/placeholder.svg",
      ],
      features: ["Ocean View", "Private Balcony", "Concierge", "Pool", "Gym"],
      yearBuilt: 2020,
      agent: mockAgents[2],
    },
    {
      id: "prop4",
      title: "Cozy Studio Apartment",
      description: "Charming studio apartment in a historic building, perfect for young professionals or students.",
      price: 1800,
      type: "rent",
      bedrooms: 0,
      bathrooms: 1,
      squareFeet: 550,
      location: "101 Pine St, Boston, MA",
      images: [
        "/images/placeholder.svg",
        "/images/placeholder.svg",
        "/images/placeholder.svg",
      ],
      features: ["Utilities Included", "Pet Friendly", "Furnished", "Laundry in Building"],
      yearBuilt: 1920,
      agent: mockAgents[0],
    },
    {
      id: "prop5",
      title: "Modern Townhouse",
      description: "Contemporary 3-bedroom townhouse with an open floor plan, private patio, and attached garage.",
      price: 3200,
      type: "rent",
      bedrooms: 3,
      bathrooms: 2.5,
      squareFeet: 1800,
      location: "222 Maple Dr, Seattle, WA",
      images: [
        "/images/placeholder.svg",
        "/images/placeholder.svg",
        "/images/placeholder.svg",
      ],
      features: ["Attached Garage", "Private Patio", "Stainless Steel Appliances", "Smart Home Features"],
      yearBuilt: 2015,
      agent: mockAgents[1],
    },
    {
      id: "prop6",
      title: "Rustic Mountain Cabin",
      description: "Charming 2-bedroom cabin nestled in the mountains with stunning views and a cozy fireplace.",
      price: 350000,
      type: "sale",
      bedrooms: 2,
      bathrooms: 1,
      squareFeet: 1100,
      location: "333 Mountain Rd, Denver, CO",
      images: [
        "/images/placeholder.svg",
        "/images/placeholder.svg",
        "/images/placeholder.svg",
      ],
      features: ["Mountain Views", "Fireplace", "Wood Floors", "Large Deck"],
      yearBuilt: 1985,
      agent: mockAgents[2],
    },
  ]
  
  // Mock Users
  export const mockUsers = [
    {
      id: "user1",
      name: "John Doe",
      email: "john.doe@example.com",
      phone: "(123) 456-7893",
      photo: "/placeholder.svg?height=200&width=200",
      savedProperties: ["prop1", "prop3"],
      role: "buyer",
    },
    {
      id: "user2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      phone: "(123) 456-7894",
      photo: "/placeholder.svg?height=200&width=200",
      savedProperties: ["prop2"],
      listings: ["prop4", "prop5"],
      role: "both",
    },
  ]