// Mock Agents
export const mockAgents = [
  {
    id: "agent1",
    name: "Sarah Johnson",
    email: "sarah.johnson@realestate.com",
    phone: "(123) 456-7890",
    photo: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "agent2",
    name: "Michael Chen",
    email: "michael.chen@realestate.com",
    phone: "(123) 456-7891",
    photo: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "agent3",
    name: "Jessica Williams",
    email: "jessica.williams@realestate.com",
    phone: "(123) 456-7892",
    photo: "/placeholder.svg?height=200&width=200",
  },
]

// Mock Users
export const mockUsers = [
  {
    id: "buyer1",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "(123) 456-7893",
    photo: "/images/placeholder.svg",
    savedProperties: ["prop1", "prop3"],
    role: "buyer",
  },
  {
    id: "seller1",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "(123) 456-7894",
    photo: "/images/placeholder.svg",
    savedProperties: [],
    listings: ["prop1", "prop2"],
    role: "seller",
  },
  {
    id: "seller2",
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    phone: "(123) 456-7895",
    photo: "/images/placeholder.svg",
    savedProperties: [],
    listings: ["prop3", "prop6"],
    role: "seller",
  },
  {
    id: "seller3",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "(123) 456-7896",
    photo: "/images/placeholder.svg",
    savedProperties: [],
    listings: ["prop7", "prop8"],
    role: "seller",
  },
]

// Mock Properties - Removed all rent type properties
export const mockProperties = [
  {
    id: "prop1",
    title: "Modern Downtown Apartment",
    description:
      "Luxurious 2-bedroom apartment in the heart of downtown with stunning city views, modern appliances, and access to premium amenities including a gym, pool, and rooftop terrace.",
    price: 450000,
    type: "sale",
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    location: "123 Main St, New York, NY",
    sellerId: "seller1",
    images: [
      "/images/placeholder.svg",
      "/images/placeholder.svg",
      "/images/placeholder.svg",
    ],
    features: ["Hardwood Floors", "Central AC", "In-unit Laundry", "Balcony", "Parking"],
    yearBuilt: 2018,
    agent: mockAgents[0],
    reviews: [
      {
        id: "rev1",
        userId: "user1",
        userName: "John Doe",
        rating: 4,
        comment: "Great property, excellent location!",
        date: "2023-05-15",
      },
    ],
  },
  {
    id: "prop2",
    title: "Spacious Family Home",
    description:
      "Beautiful 4-bedroom family home in a quiet suburban neighborhood with a large backyard, updated kitchen, and finished basement.",
    price: 750000,
    type: "sale",
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2800,
    location: "456 Oak Ave, Chicago, IL",
    sellerId: "seller1",
    images: [
      "/images/placeholder.svg",
      "/images/placeholder.svg",
      "/images/placeholder.svg",
    ],
    features: ["Finished Basement", "Backyard", "Garage", "Fireplace", "Updated Kitchen"],
    yearBuilt: 2005,
    agent: mockAgents[1],
  },
  {
    id: "prop3",
    title: "Luxury Waterfront Condo",
    description:
      "Stunning 3-bedroom waterfront condo with panoramic ocean views, high-end finishes, and resort-style amenities.",
    price: 1200000,
    type: "sale",
    bedrooms: 3,
    bathrooms: 3.5,
    squareFeet: 2200,
    location: "789 Beach Blvd, Miami, FL",
    sellerId: "seller2",
    images: [
      "/images/placeholder.svg",
      "/images/placeholder.svg",
      "/images/placeholder.svg",
    ],
    features: ["Ocean View", "Private Balcony", "Concierge", "Pool", "Gym"],
    yearBuilt: 2020,
    agent: mockAgents[2],
  },
  {
    id: "prop6",
    title: "Rustic Mountain Cabin",
    description: "Charming 2-bedroom cabin nestled in the mountains with stunning views and a cozy fireplace.",
    price: 350000,
    type: "sale",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 1100,
    location: "333 Mountain Rd, Denver, CO",
    sellerId: "seller2",
    images: [
      "/images/placeholder.svg",
      "/images/placeholder.svg",
      "/images/placeholder.svg",
    ],
    features: ["Mountain Views", "Fireplace", "Wood Floors", "Large Deck"],
    yearBuilt: 1985,
    agent: mockAgents[2],
  },
  {
    id: "prop7",
    title: "Contemporary Urban Loft",
    description: "Stylish loft in the arts district with high ceilings, exposed brick, and modern finishes.",
    price: 525000,
    type: "sale",
    bedrooms: 1,
    bathrooms: 1.5,
    squareFeet: 1050,
    location: "555 Artist Way, Portland, OR",
    sellerId: "seller3",
    images: [
      "/images/placeholder.svg",
      "/images/placeholder.svg",
      "/images/placeholder.svg",
    ],
    features: ["High Ceilings", "Exposed Brick", "Open Floor Plan", "Stainless Appliances"],
    yearBuilt: 2008,
    agent: mockAgents[0],
  },
  {
    id: "prop8",
    title: "Suburban Ranch Home",
    description: "Well-maintained ranch home on a corner lot with updated kitchen and bathrooms.",
    price: 425000,
    type: "sale",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1800,
    location: "777 Maple Street, Austin, TX",
    sellerId: "seller3",
    images: [
      "/images/placeholder.svg",
      "/images/placeholder.svg",
      "/images/placeholder.svg",
    ],
    features: ["Corner Lot", "Updated Kitchen", "Patio", "Attached Garage"],
    yearBuilt: 1995,
    agent: mockAgents[1],
  },
]



